version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  app-prod:
    build:
      context: .
      target: production
    ports:
      - "8001:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 